### ISSUE TITLE
Minor text render issue w/ spurious text

### ISSUE THREAD

**Issue by jananiravi** [r-lib/conflicted#1]
Thanks @hadley for releasing this _really useful_ package!

Was just testing this out with the `README` examples and found a couple of text render issues (w/ junk characters):
### e.g. 1
![image](https://user-images.githubusercontent.com/8397074/40312908-2b0a7356-5ce2-11e8-9a86-a6b7c2f841c2.png)

### e.g.2
![image](https://user-images.githubusercontent.com/8397074/40312921-37f8385a-5ce2-11e8-9ad1-e73dfba3fc40.png)

**Comment by krlmlr** [comment]
These are most likely ANSI escapes, can you try setting `options(crayon.enabled = FALSE)` ?

**Comment by jananiravi** [comment]
Thanks, @krlmlr! That fixes it, but since this is not a part of any _easily findable_ ANSI options listed in preferences, is there any way you could add an error message or include this `options()` line in the package code? That would be most helpful.

**Comment by gaborcsardi** [comment]
@jananiravi This probably happens because of a misconfigured system, or a bug in the crayon package. What is your `sessioninfo::session_info()` output?

**Comment by gaborcsardi** [comment]
> Here it is @gaborcsardi:

I mean, from the session that actually fails.

> Also, @krlmlr I'm having to use the options() for each new session.

Put it in your R profile.
