### ISSUE TITLE
"summarize()" isn't considered to be in dplyr, even though it's a synonym for "summarise()"

### ISSUE THREAD

**Issue by BorgeJorge** [r-lib/conflicted#109]
Listed as synonyms [here](https://dplyr.tidyverse.org/reference/summarise.html).

**Comment by hadley** [comment]
What's the issue?

**Comment by BorgeJorge** [comment]
Apologies for not going into more detail. Noodling around a little more, it looks to be maybe a display issue, and/or associated with duckplyr. The output from these commands:
```r
library(dplyr)
library(duckplyr)
library(Hmisc)
library(conflicted)
mtcars %>% summarize(mean = mean(disp))
```
suggests that duckplyr masks ```dplyr::summarize()``` without acknowledging it. Then conflicted() doesn't list ```dplyr::summarize()```.  But maybe ```summarize()``` is the same in dplyr and duckplyr? (In any case they operate the same in this circumstance.)

<details>

RStudio output:
![image](https://github.com/r-lib/conflicted/assets/47008223/b3beb613-854e-40a1-9aea-7ee15952f237)

</details>

**Comment by hadley** [comment]
Text reprex:

``` r
library(conflicted)
library(dplyr)
library(duckplyr)
#> The duckplyr package is configured to fall back to dplyr when it encounters an
#> incompatibility. Fallback events can be collected and uploaded for analysis to
#> guide future development. By default, no data will be collected or uploaded.
#> → Run `duckplyr::fallback_sitrep()` to review the current settings.
#> ✔ Overwriting dplyr methods with duckplyr methods.
#> ℹ Turn off with `duckplyr::methods_restore()`.
library(Hmisc)

summarize
#> Error:
#> ! [conflicted] summarize found in 2 packages.
#> Either pick the one you want with `::`:
#> • Hmisc::summarize
#> • duckplyr::summarize
#> Or declare a preference with `conflicts_prefer()`:
#> • `conflicts_prefer(Hmisc::summarize)`
  #> • `conflicts_prefer(duckplyr::summarize)`
```

<sup>Created on 2024-10-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

`identical(duckplyr::summarize, dplyr::summarise)` is FALSE so I suspect this is some trickier that duckdplyr is doing. Unfortunately I don't think there's much that conflicted can do about it.
