### ISSUE TITLE
Can conflicted be used as an alternative to `extenal_package::func` in package development?

### ISSUE THREAD

**Issue by travis-leith** [r-lib/conflicted#111]
This is asked but not (at time of writing) answered here: https://stackoverflow.com/questions/78734567/is-it-safe-to-use-conflicted-instead-of-fully-qualifying-namespaces-for-packag

Is it safe to use conflicted in package development. Would doing so avoid a user from unintentionally overriding a function my package depends on for example?

I'd like to disambiguate style guidelines and conventions from actual consequences of using conflicted in package development.
If it turns out that it is not safe, can we make this clear in the readme for conflicted?

**Comment by hadley** [comment]
No 😄

**Comment by travis-leith** [comment]
Fair enough 😄. I will close this, because if anyone should be trusted with a one word answer on this topic it would be you. Having said that, feel free to add (or link to) a brief explanation.
