### ISSUE TITLE
Order when attaching with library()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/conflicted#12]
The position of a package in the search path depends solely on the load order, disregarding dependencies. In the first example, _dplyr_ comes after _tibble_ in the search path, even though _dplyr_ imports _tibble_. Perhaps it doesn't matter much, but it feels more consistent if the packages are ordered topologically (w.r.t. to the dependency graph) in the search path.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tibble)
search()[1:4]
#> [1] ".GlobalEnv"     "package:tibble" "package:dplyr"  "package:stats"
```

> Created on 2018-06-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

``` r
library(tibble)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
search()[1:4]
#> [1] ".GlobalEnv"     "package:dplyr"  "package:tibble" "package:stats"
```

> Created on 2018-06-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
This feels like it's currently outside of the scope of conflicted.
