### ISSUE TITLE
How do I specify which %in% to use?

### ISSUE THREAD

**Issue by Breza** [r-lib/conflicted#13]
I'm having trouble using `%in%` with conflicted. The function works when R is in a clean state.

```
library(conflicted)

"A" %in% LETTERS
# [1] TRUE
```

The package `h2o` also declares the function `%in%`, which throws an error from conflicted.

```
library(conflicted)
library(h2o)
"A" %in% LETTERS
# Error: %in% found in 2 packages. You must indicate which one you want with ::
#  * h2o::%in%
#  * base::%in%
```

How can I specify which package's `%in%` I want to use? Copying and pasting the recommendation doesn't work.

```
"A" base::%in% LETTERS
# Error: unexpected symbol in ""A" base"
```

I thought that using backticks around the function name would help, but that still doesn't work.

```
"A" base::`%in%` LETTERS
# Error: unexpected symbol in ""A" base"
```

Any ideas?

**Comment by jon-harmon-macmillan** [comment]
I know it looks strange, but:
``base::`%in%`("A", LETTERS)``

**Comment by Breza** [comment]
Thanks, that works!

**Comment by hadley** [comment]
Reopening, because conflicted should put the `` ` `` around it for you.

In your case, I'd recommend doing

```R
`%in%` <- base::`%in%`
```
