### ISSUE TITLE
maybe a bug: why block the inner function calls in packages? 

### ISSUE THREAD

**Issue by motheeyue** [r-lib/conflicted#16]
I my under stand, the 'conficted' should only block the user defined function on naming ambiguity, but I meet a strange case as below:
**base::as.Date(base::intersect(idx[1:10], idx[7:15]))**

**Error: as.Date.numeric found in 2 packages. You must indicate which one you want with ::
 * zoo::as.Date.numeric
 * base::as.Date.numeric**

in my understanding, it should not block this function 'base::as.Date', but it rerport an error. why the inside called function is blocked by 'conflicted'?

**Comment by motheeyue** [comment]
but when I call below function, it worked. I think zoo::as.Date was not blocked because it may did not call the function zoo::as.Date.numeric.
zoo::as.Date(base::intersect(idx[1:10], idx[7:15]))
[1] "2007-01-07" "2007-01-08" "2007-01-09" "2007-01-10"

**Comment by hadley** [comment]
And is resolved in the dev version:

``` r
library(conflicted)
library(zoo)

as.Date(32768, origin = "1900-01-01")
#> [1] "1989-09-19"
base::as.Date(32768, origin = "1900-01-01")
#> [1] "1989-09-19"


conflicts_find(c("zoo", "base"))
#> 2 conflicts
#> * `as.Date`        : [zoo]
#> * `as.Date.numeric`: [zoo]
```

Created on 2018-08-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
