### ISSUE TITLE
Consider (optional?) warnings rather than errors?

### ISSUE THREAD

**Issue by devillemereuil** [r-lib/conflicted#26]
The fact that conflicted issue an error can break many things, to the point where conflicted cannot even be loaded. For example, the IDE RKWard overwrites `require` to account for its own way to install packages and that breaks loading conflicted:

````R
> library(conflicted)
Error: package or namespace load failed for ‘conflicted’:
 .onAttach failed in attachNamespace() for 'conflicted', details:
  call: NULL
  error: require found in 2 packages. You must indicate which one you want with ::
 * rkward::require
 * base::require
````

This is just one example, but as far as I like the idea behind `conflicted`, having scripts being stopped "just" because of namespace conflicts is not a cost I would like to pay for using the package. I would find it most useful if it was throwing warnings instead (then I know I have to take care of the conflict, yet my script still runs if this is what I need right now).

So I'm humbly suggesting either to yield warnings instead of errors by default, or make the level of output (warning/error) configurable.

**Comment by hadley** [comment]
If you are seeing these conflicts from a package, then that package is not using NAMESPACE definitions correctly, and the package has the same risk of finding the wrong function as your script code does. In this case, I think you should file an issue with the package maintainer alerting them to the problem with their package.

**Comment by devillemereuil** [comment]
That was... not really the point, but I hear you don't want to consider issuing warnings instead of errors, which is your call to make in the end.

**Comment by hadley** [comment]
There is a legitimate conflict, which someone needs to resolve. You can resolve it yourself in the CRAN version of conflict, but really it's the job of the package author.

**Comment by devillemereuil** [comment]
I think you misunderstood. The conflict I highlighted is merely to illustrate that the fact `conflicted` notice the user of a conflict using errors (which stops the execution) can be cumbersome (maybe something needs to be fixed somewhere, yes, but meanwhile, `conflicted` doesn't load at all in RKWard), while using warnings would still allow the script/package/code to execute.

My point was less about this particular conflict than about `conflicted` policy to interact with the user using errors rather than warnings. Maybe I'm not using the most accurate words here, please excuse me if that's the case.

**Comment by devillemereuil** [comment]
Maybe it's be easier with a MWE. Say I am doing this:
````R
> library(tidyverse)
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.0.0     ✔ purrr   0.2.4
✔ tibble  1.4.2     ✔ dplyr   0.7.4
✔ tidyr   0.8.0     ✔ stringr 1.3.1
✔ readr   1.1.1     ✔ forcats 0.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
> library(conflicted)
> iris %>% filter(Species == "setosa")
Error: filter found in 2 packages. You must indicate which one you want with ::
 * dplyr::filter
 * stats::filter
````
The line `iris %>% filter(Species == "setosa")` is not executed because of the conflict. What I am suggesting is that we could have this instead:
````R
> iris %>% filter(Species == "setosa")
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
Warning: filter found in 2 packages. You must indicate which one you want with ::
 * dplyr::filter
 * stats::filter
````

Now, I would understand why one could insist on having an error instead of a warning, but I feel using warnings also allow for a more widespread use of `conflicted` and was suggesting maybe an environment option could switch between both behaviours.

In the hope this is clearer (maybe you can forget about the RKWard example if it's confusing for some reason).

**Comment by hadley** [comment]
Oh ok, I was confused by your RKWard example — your actual concern seems unrelated.  But choosing errors rather than warnings was deliberate, as I think whenever there is a conflict it's better to forcefully illuminate it. Using warnings rather than errors would not be in keeping with the overall purpose of the conflicted package.

**Comment by devillemereuil** [comment]
Except when the conflict in within a loaded package the user has little control on? But maybe I misunderstands how loaded package are handled as it seems I didn't grasp what's happening my first example.

Anyway, it was a suggestion and I kind of expected this was an opinionated decision to start with, but I thought it'd be worth raising the matter.
