### ISSUE TITLE
conflicted errors coming from imported packages

### ISSUE THREAD

**Issue by wolski** [r-lib/conflicted#27]
Although in my code I am not using the function `layout` calling `heatmap3::heatmap3`

causes the following error:
Error: layout found in 2 packages. You must indicate which one you want with ::
 * plotly::layout
 * graphics::layout

Since the call is not made from my code I can not "choose which function to use." [Package description of conflicted]( https://cran.r-project.org/web/packages/conflicted/index.html)

How to proceed in such a case?

**Comment by batpigandme** [comment]
That does sound strange. The [`heatmap3()`](https://rdrr.io/cran/heatmap3/src/R/heatmap3.R) code uses `layout()` but neither of those are dependencies, so I would think you'd have at least plotly loaded locally.

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Thanks

**Comment by wolski** [comment]
Here is the `reprex` 

```{r setup, include=FALSE}
library(conflicted)
library(heatmap3)
library(plotly)
?heatmap3


# copy pasted from the heatmap3 example.

set.seed(123456789)
rnormData<-matrix(rnorm(1000), 40, 25)
rnormData[1:15, seq(6, 25, 2)] = rnormData[1:15, seq(6, 25, 2)] + 2
rnormData[16:40, seq(7, 25, 2)] = rnormData[16:40, seq(7, 25, 2)] + 4
colnames(rnormData)<-c(paste("Control", 1:5, sep = ""), paste(c("TrtA", "TrtB"),
rep(1:10,each=2), sep = ""))
rownames(rnormData)<-paste("Probe", 1:40, sep = "")
ColSideColors<-cbind(Group1=c(rep("steelblue2",5), rep(c("brown1", "mediumpurple2"),10)),
    Group2=sample(c("steelblue2","brown1", "mediumpurple2"),25,replace=TRUE))
colorCell<-data.frame(row=c(1,3,5),col=c(2,4,6),color=c("green4","black","orange2"),
    stringsAsFactors=FALSE)
highlightCell<-data.frame(row=c(2,4,6),col=c(1,3,5),color=c("black","green4","orange2"),
    lwd=1:3,stringsAsFactors=FALSE)
#A simple example
heatmap3(rnormData,ColSideColors=ColSideColors,showRowDendro=FALSE,colorCell=colorCell,
    highlightCell=highlightCell)

```

**Comment by hadley** [comment]
The heatmap3 [NAMESPACE](https://cran.r-project.org/web/packages/heatmap3/NAMESPACE) doesn't import the `layout()` function, so I think this is an issue with that package. conflicted is reporting a legitimate conflict — and if you install the latest CRAN version, you'll be able to resolve it using the new `conflict_prefer()` function.
