### ISSUE TITLE
User Request: conflicted::enable_conflicted()

### ISSUE THREAD

**Issue by jtelleria** [r-lib/conflicted#31]
It might be useful to create new functions: 

```{r}
conflicted::enable_conflicted()
conflicted::disable_conflicted()
```

In order to include conflicted in the tidyverse package.

By default, when you execute:
```{r}
library(conflicted)
```
The package could be enabled by default. But with tidyverse:
```{r}
library(tidyverse)
```
The package could be included, but not enabled, and raise a message saying that it could be enabled, till the users get used to the "conflicted" library, and adapt their code. 

And in the future, vice versa, the package could be enabled by default, and give the option of disabling it.

**Comment by hadley** [comment]
The idea of conflicted is that you activate it by attaching the package, so this seems like it's out of scope.
