### ISSUE TITLE
Error on completion

### ISSUE THREAD

**Issue by heavywatal** [r-lib/conflicted#32]
I use `/usr/local/bin/R` from command line on macOS and <kbd>TAB</kbd> key for code completion, which seems not compatible with this package. It shows superfluous errors on parameter name completion. For example, if I press <kbd>TAB</kbd> key after this,
```
library(conflicted)
library(dplyr)
dplyr::lag(
```
then the following error is printed:
```
dplyr::lag(Error: [conflicted] `lag` found in 2 packages.
Either pick the one you want with `::`
* dplyr::lag
* stats::lag
Or declare a preference with `conflict_prefer()`
* conflict_prefer("lag", "dplyr")
* conflict_prefer("lag", "stats")
```

**Comment by lefeverde** [comment]
I also have this issue on mac with `conflicted` version `1.0.1.9000`.

**Comment by hadley** [comment]
Unfortunately it doesn't look like there's anything I can do about this — the built-in tab completion must look up the function in the global environment, rather than using the information in `::`
