### ISSUE TITLE
Info Only - Alternate strategy: prioritize first package to load

### ISSUE THREAD

**Issue by MPagel** [r-lib/conflicted#33]
Related to #4 and #12 (and https://github.com/tidyverse/lubridate/issues/705)
I posted some code in a lubridate "issue" that, if used within library packages, could be used to limit function masking by later-loaded libraries.

https://github.com/tidyverse/lubridate/issues/742#issuecomment-451592137

I'm sure there are better ways to go about this, but perhaps this will plant a seed in someone's mind.

**Comment by hadley** [comment]
That behaviour is unfortunately out of scope for conflicted.
