### ISSUE TITLE
R 3.6 conflict library

### ISSUE THREAD

**Issue by olesendan** [r-lib/conflicted#40]
Hi.

after updating to R 3.6.0 I'm expering in Rstudio that after loading conflicted, then I need to prefix library with base::

this was not the case before the update, which I did a couple of days ago.
is this an expected behaviour?

Greetings from Denmark
Dan Olesen

**Comment by hadley** [comment]
I've never seen this problem, it's been >2 years, and you didn't supply a reprex or a backtrace, so I'm going to close.
