### ISSUE TITLE
conflicted does not shows conflict with base R function

### ISSUE THREAD

**Issue by vasili111** [r-lib/conflicted#47]
For example this code:

```
library(conflicted)

library(geepack)
library(PairedData)
library(Matrix)

timeorder <- rep(1:5, 6)
tvar <- timeorder + rnorm(length(timeorder))
idvar <- rep(1:6, each=5)
uuu <- rep(rnorm(6), each=5)
yvar <- 1 + 2*tvar + uuu + rnorm(length(tvar))
simdat <- data.frame(idvar, timeorder, tvar, yvar)

mod1 <- geeglm(yvar~tvar, id=idvar, data=simdat, corstr="ar1")

summary(mod1)
```
output:
```
Error: [conflicted] `summary` found in 2 packages.
Either pick the one you want with `::` 
* Matrix::summary
* PairedData::summary
Or declare a preference with `conflict_prefer()`
* conflict_prefer("summary", "Matrix")
* conflict_prefer("summary", "PairedData")
```
In fact there are 3 sammary functions here: `base::summary`, `Matrix::summary` and `PairedData::summary`. But only `Matrix::summary` and `PairedData::summary` are reported. Is it bug or there is any solution for it?

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(conflicted)

library(PairedData)
#> Loading required package: MASS
#> Loading required package: gld
#> Loading required package: mvtnorm
#> Loading required package: lattice
#> Loading required package: ggplot2
library(Matrix)

summary
#> Error: [conflicted] `summary` found in 2 packages.
#> Either pick the one you want with `::` 
#> * Matrix::summary
#> * PairedData::summary
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("summary", "Matrix")
#> * conflict_prefer("summary", "PairedData")
```

<sup>Created on 2021-11-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think the issue here is that neither `Matrix::summary` nor `PairedData::summary` conflict with `base::summary`, but they conflict with one another.

**Comment by hadley** [comment]
Even more minimal reprex:

``` r
conflicted::conflict_scout(c("PairedData", "Matrix"))
#> 1 conflict:
#> * `summary`: PairedData, Matrix
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think it should actually be this:

``` r
conflicted::conflict_scout(c("base", "PairedData", "Matrix"))
#> 3 conflicts:
#> * `chol2inv`: base, Matrix
#> * `rcond`   : base, Matrix
#> * `summary` : base, PairedData, Matrix
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

And the first two aren't right either because Matrix's `rcond` and `chol2inv` are just S4 generic versions of the base functions so shouldn't technically be conflicts either

**Comment by hadley** [comment]
Now we get:

``` r
conflicted::conflict_scout(c("base", "PairedData", "Matrix"))
#> 1 conflict:
#> * `summary`: base, PairedData, Matrix
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
