### ISSUE TITLE
Method to remove preferences

### ISSUE THREAD

**Issue by TylerGrantSmith** [r-lib/conflicted#50]
What if any is the preferred method to remove `conflicted` preferences?  
For example, if I do 
```
library(dplyr)
library(MASS)

conflicted::conflict_prefer("select", "dplyr")
```
What would I do to remove that preference later on?  It would seem that `conflicted:::conflicts_remove("dplyr")` should work, but then, why isn't it exported?  Also, what would I do to remove a preference for one particular function, not just overwrite it with a new preference?

**Comment by moodymudskipper** [comment]
You could use base R the following way, given that `conflicted` works by storing in a `conflicts` environment variables bound to the relevant package function. The calls you'd want are :

    rm("select", envir = as.environment(".conflicts"))
    rm(list = intersect(ls("package:dplyr"), ls(".conflicts")), envir = as.environment(".conflicts"))

See : 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(MASS)
#> 
#> Attaching package: 'MASS'
#> The following object is masked from 'package:dplyr':
#> 
#>     select

conflicted::conflict_prefer("select", "dplyr")
#> [conflicted] Will prefer dplyr::select over any other package
search()
#>  [1] ".GlobalEnv"        ".conflicts"        "package:MASS"     
#>  [4] "package:dplyr"     "package:stats"     "package:graphics" 
#>  [7] "package:grDevices" "package:utils"     "package:datasets" 
#> [10] "package:methods"   "Autoloads"         "tools:callr"      
#> [13] "package:base"
ls(".conflicts")
#> [1] "filter"    "intersect" "lag"       "library"   "require"   "select"   
#> [7] "setdiff"   "setequal"  "union"
rm("select", envir = as.environment(".conflicts"))
ls(".conflicts")
#> [1] "filter"    "intersect" "lag"       "library"   "require"   "setdiff"  
#> [7] "setequal"  "union"
select
#> function (obj) 
#> UseMethod("select")
#> <bytecode: 0x00000000188aa3e0>
#> <environment: namespace:MASS>
rm(list = intersect(ls("package:dplyr"), ls(".conflicts")), envir = as.environment(".conflicts"))
ls(".conflicts")
#> [1] "library" "require"
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@TylerGrantSmith I don't think we want to export this functionality; I think you're better off just starting with a clean session.

@moodymudskipper it's not a good idea to recommend reaching into the internals of a package. That code will break if we ever  decide to change the data structures we use internally.
