### ISSUE TITLE
Feature request: ability to prefer all functions in package

### ISSUE THREAD

**Issue by rossellhayes** [r-lib/conflicted#51]
Certain packages, like [tidylog](https://github.com/elbersb/tidylog) and [wisegroup](https://github.com/MilesMcBain/wisegroup), are designed to mask multiple functions in another package. If these packages are used with conflicted, the user will have to include numerous calls to `conflict_prefer()` to avoid errors. An alternative is to provide a function, e.g. `conflict_always_prefer()`, that allows the user to prefer all functions exported from a package.

One way to implement this would be:
``` r
conflict_always_prefer <- function(winner, losers = NULL, quiet = FALSE) {
  invisible(
    lapply(getNamespaceExports(winner), conflict_prefer, winner, losers, quiet)
  )
}

# For example
conflict_always_prefer(winner = "tidylog", losers = c("dplyr", "tidyr"))
```

**Comment by kiernann** [comment]
This is also the case for vroom and readr. I'd like to `conflict_prefer()` the `here::here()` function over `lubridate::here()` yet not have to specify every `vroom::col_*()` function.

**Comment by moodymudskipper** [comment]
What about an additional `regex = FALSE` argument to `conflict_prefer`, we could do `conflict_prefer(".*", "tidylog", regex = TRUE)` to prefer all tidylog functions, or `conflict_prefer("col_.*", "vroom", regex = TRUE)` to prefer all `vroom::col_*()` functions.

**Comment by rossellhayes** [comment]
> What about an additional `regex = FALSE` argument to `conflict_prefer`, we could do `conflict_prefer(".*", "tidylog", regex = TRUE)` to prefer all tidylog functions, or `conflict_prefer("^col_.*", "vroom", regex = TRUE)` to prefer all `vroom::col_*()` functions.

I think this is an excellent solution!

**Comment by hadley** [comment]
Implemented as `conflict_prefer_all()` and `conflict_prefer_matching()`.
