### ISSUE TITLE
Option to warn/track instead of error on conflicts?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [r-lib/conflicted#52]
When converting a script that was not written with conflicted in mind, it would be nice if I could load conflicted in some kind of "passive" mode where it tracked each time a conflicted function name was used without first resolving the conflict, and emitted a warning for it, but allowed execution to continue using R's default conflict resolution. Then it could have a function similar to `conflict_scout` that only reports on conflicted names that were actually *used*.

**Comment by DarwinAwardWinner** [comment]
Alternatively, it might be nice to have a function to statically analyze a source file for conflicts.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think this is out of scope for conflicted: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
