### ISSUE TITLE
RStudio session becomes non-responsive after a conflict

### ISSUE THREAD

**Issue by genec1** [r-lib/conflicted#57]
I'm working in an RStudio client session and just started using `conflicted`.  I'm finding that during an interactive run in an R Markdown file, after a conflict comes up and `conflicted` reports an error, the session becomes non-responsive.

I'm running RStudio Server Version 1.3.1073, R version 4.0.3

**Comment by slamander** [comment]
I'm experiencing the same issue as @genec1; in fact, my session goes non-responsive after simply loading the package with `library`.

**Comment by kevinushey** [comment]
Any chance you can share a reproducible example?

**Comment by kevinushey** [comment]
I've reproduced the issue; I believe it may be an issue in the RStudio IDE and so have filed https://github.com/rstudio/rstudio/issues/10093.

**Comment by kevinushey** [comment]
@kanefos, what version of RStudio are you using? The issue should already be resolved in the latest release.

**Comment by kanefos** [comment]
yes apologies all fixed now! thanks @kevinushey

**Comment by kevinushey** [comment]
Great, thanks for confirming!
