### ISSUE TITLE
as.DATE formatting returning NA values

### ISSUE THREAD

**Issue by dmstyers** [r-lib/conflicted#66]
Hello. I am very new to R and not very good at troubleshooting. A friend wrote some script for me to read in an excel file of climate data to summarize for a class of mine. The file reads in fine but then the first line of code below returns the errors written out below it. The odd thing is that this script works fine on her computer but not on mine. I have installed the latest version of R studio and updated all packages.
_____________________________________________________________
climate$DATE <- as.Date(climate$DATE, "%m/%d/%Y")

Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric
_____________________________________________________________
Any suggestions are greatly appreciated. Thanks in advance!

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
