### ISSUE TITLE
Error from conflicted are not easy to copy paste

### ISSUE THREAD

**Issue by sanjmeh** [r-lib/conflicted#69]
This is not a bug but an improvement suggestion. When conflicted throws an error it rightly so also advises an explicit declaration to prefer one packageover the other. However the text error message has back slashes that make it hard to copy paste. See screenshot.
<img width="792" alt="Screenshot 2022-09-10 at 10 11 29 PM" src="https://user-images.githubusercontent.com/3091624/189493559-0ca85415-0b83-482f-a521-8babee57b5db.png">

### RSTUDIO version
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Ubuntu Bionic
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

**Comment by krlmlr** [comment]
Thanks. This seems due to how the error message is extracted, in some code that's not shown in the screenshot. I'm seeing:

``` r
library(conflicted)
library(tidyverse)
library(data.table)
library(xts)
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric

last(1:3)
#> Error:
#> ! [conflicted] `last` found in 3 packages.
#> Either pick the one you want with `::` 
#> * xts::last
#> * data.table::last
#> * dplyr::last
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("last", "xts")
#> * conflict_prefer("last", "data.table")
#> * conflict_prefer("last", "dplyr")
```

<sup>Created on 2022-09-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sanjmeh** [comment]
I think you cal close this, as I see the format changes only when the error is logged using futile.logger. So I am not sure if it is a problem in futile.logger itself.
