### ISSUE TITLE
Prioritize packages

### ISSUE THREAD

**Issue by jnolis** [r-lib/conflicted#7]
Hi! I have a potential feature request:

Would it be possible to have the ability to prioritize packages during conflicts? That is to say if I have PackageA and PackageB, given a conflict I always want to use PackageB over PackageA, rather than using the order I load them in?

I'm not sure how exactly this would be implemented, but I imagine this happens often in practice (like dplyr is always used over plyr).

Thanks!

**Comment by hadley** [comment]
If you want this behaviour, don't use conflicted 😄 

More seriously, I think conflicted will gain some helpers for prioritising specific function (see #4), but I think if its easy to prioritise whole packages we'll end up in the situation I'm trying to avoid.

**Comment by jnolis** [comment]
Hah, fair enough!
