### ISSUE TITLE
FR: Prefer an entire package in one call

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/conflicted#83]
So that the order of `library()` calls can be safely ignored.

In this case all `dplyr` functions would be preferred even with multiple conflicts coming from different packages.

``` r
library(conflicted)
library(dplyr)
library(MASS)

package_prefer(dplyr)

select(mtcars, mpg, cyl)
```

**Comment by hadley** [comment]
`conflict_prefer_all()` ? You get a lot of messaging, but I'm not sure how you could otherwise avoid that.
