### ISSUE TITLE
later one automatically takes precendence when accidentally using multiple conflicts_prefer with same object name

### ISSUE THREAD

**Issue by deepjyot1991** [r-lib/conflicted#89]
I love this package as I believe it is the best way to resolve conflicts efficiently. However I did notice that if you accidentally use conflicts_prefer for an object (function) from multiple packages, it doesn't generate any error.

Example:

`conflicts_prefer(dplyr::summarize)`
after a few lines of code ...
`conflicts_prefer(plyr::summarize)`

In above case plyr takes precedence. Wouldn't it be better if it were to throw an error instead?

**Comment by hadley** [comment]
The current behaviour makes sense to me — it’s ok to change your preferences.
