### ISSUE TITLE
as.Date function conflict message

### ISSUE THREAD

**Issue by LukaIgnjatovic** [r-lib/conflicted#9]
When I load the 'zoo' package, this line of code:

`base::as.Date(x = foo, format = "bar")`

persistently gives me this warning message:

`Error: as.Date found in 2 packages. You must indicate which one you want with ::`
` * zoo::as.Date`
` * base::as.Date`

This message is later present after every line of code I execute.

**Comment by batpigandme** [comment]
Yes, this is what conflicted expressly does — you either have to specify with `::` notation, or declare which one you want for the session using:

**Comment by batpigandme** [comment]
Oh, unless you mean you're already doing that and you're still getting that message… 

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Right now the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```

**Comment by jimhester** [comment]
A reprex would be

``` r
library(zoo)
library(conflicted)
base::as.Date(32768, origin = "1900-01-01")
#> Error: as.Date.numeric found in 2 packages. You must indicate which one you want with ::
#>  * zoo::as.Date.numeric
#>  * base::as.Date.numeric
```

Created on 2018-06-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

The problem is zoo has conflicts with both the generic `as.Date` as well as the `as.Date.numeric` method. You can fix this by explicitly defining both of them

``` r
library(zoo)
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
library(conflicted)
#> Warning: package 'conflicted' was built under R version 3.4.4

as.Date <- base::as.Date
as.Date.numeric <- base::as.Date.numeric

as.Date(32768, origin = "1900-01-01")
#> [1] "1989-09-19"
```

**Comment by LukaIgnjatovic** [comment]
Yes Jim, that would be the reprex. Thanks!

**Comment by hadley** [comment]
Hmmmm, does this function obey the superset principle? I think so because all zoo appears to do is add a default `origin` to `as.Date.numeric`.
